version: '3.5'

services:
  ttrss:
    image: dannytsang/ttrss:latest
    container_name: ttrss
    restart: always
    environment:
      - TZ="Europe/London"
    volumes:
      - config:/config
      - feed_icon_cache:/usr/share/nginx/html/feed-icons
      - /var/log:/var/log
      - plugins:/usr/share/nginx/html/
    ports:
        - "80:80"
        - "443:443"
volumes:
  feed_icon_cache:
    driver: local
    driver_opts:
      type: none
      device: $HOME/ttrss/feed-icons
      o: bind
  plugins:
    driver: local
    driver_opts:
      type: none
      device: $HOME/ttrss/plugins
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: $HOME/ttrss/config
      o: bind

